version: "3.8"
services:
  web:
    container_name: app_csv_generator
    build: .
    ports:
      - "8006:8006"
    command: sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8006"
    restart: always

