# Generated by Django 4.1.7 on 2023-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
