# Generated by Django 4.1.7 on 2023-03-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0002_alter_schema_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='age',
            new_name='address',
        ),
        migrations.AddField(
            model_name='schema',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='date_fake',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='domain_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='integer_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='max_value_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='min_value_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
